/********************************************************************
	created:	2010/07/25
	created:	25:7:2010   18:17
	filename: 	RendererConstants.cpp	
	author:		James
	
	purpose:	
*********************************************************************/

#include "Common.h"
#include "hRendererConstants.h"

namespace Heart
{
namespace EffectSemantics
{
#define DEFINE_SEMANTIC( x ) #x,

	const hChar* SemanticNames[] = 
	{
		DEFINE_SEMANTIC( SCREENPARAMETERS )						// EFFECTSEMANTICID_SCREENPARAMETERS,
		DEFINE_SEMANTIC( WORLDMATRIX )							// EFFECTSEMANTICID_WORLDMATRIX,
		DEFINE_SEMANTIC( INVERSEWORLDMATRIX )					// EFFECTSEMANTICID_INVERSEWORLDMATRIX,
		DEFINE_SEMANTIC( WORLDINVERSETRANSPOSEMATRIX )			// EFFECTSEMANTICID_WORLDINVERSETRANSPOSEMATRIX,
		DEFINE_SEMANTIC( VIEWMATRIX )							// EFFECTSEMANTICID_VIEWMATRIX,
		DEFINE_SEMANTIC( INVERSEVIEWMATRIX )					// EFFECTSEMANTICID_INVERSEVIEWMATRIX,
		DEFINE_SEMANTIC( INVERSETRANSPOSEVIEWMATRIX )			// EFFECTSEMANTICID_INVERSETRANSPOSEVIEWMATRIX,
		DEFINE_SEMANTIC( PROJECTIONMATRIX )						// EFFECTSEMANTICID_PROJECTIONMATRIX,
		DEFINE_SEMANTIC( INVERSEPROJECTIONMATRIX )				// EFFECTSEMANTICID_INVERSEPROJECTIONMATRIX,
		DEFINE_SEMANTIC( VIEWPROJECTIONMATRIX )					//EFFECTSEMANTICID_VIEWPROJECTIONMATRIX,
		DEFINE_SEMANTIC( INVERSEVIEWPROJECTIONMATRIX )			//EFFECTSEMANTICID_INVERSEVIEWPROJECTIONMATRIX,
		DEFINE_SEMANTIC( WORLDVIEWMATRIX )						// EFFECTSEMANTICID_WORLDVIEWMATRIX,
		DEFINE_SEMANTIC( WORLDVIEWINVERSEMATRIX )				// EFFECTSEMANTICID_WORLDVIEWINVERSEMATRIX,
		DEFINE_SEMANTIC( WORLDINVERSETRANSPOSEVIEWMATRIX )		// EFFECTSEMANTICID_WORLDINVERSETRANSPOSEVIEWMATRIX,
		DEFINE_SEMANTIC( WORLDVIEWINVERSETRANSPOSEMATRIX )		// EFFECTSEMANTICID_WORLDVIEWINVERSETRANSPOSEMATRIX,
		DEFINE_SEMANTIC( WORLDVIEWPROJMATRIX )					// EFFECTSEMANTICID_WORLDVIEWPROJECTIONMATRIX,
		DEFINE_SEMANTIC( MATERIALAMBIENT )						// EFFECTSEMANTICID_MATERIALAMBIENT,
		DEFINE_SEMANTIC( MATERIALDIFFUSE )						// EFFECTSEMANTICID_MATERIALDIFFUSE,
		DEFINE_SEMANTIC( MATERIALEMISSIVE )						// EFFECTSEMANTICID_MATERIALEMISSIVE,
		DEFINE_SEMANTIC( MATERIALSPECULAR )						// EFFECTSEMANTICID_MATERIALSPECULAR,
		DEFINE_SEMANTIC( MATERIALSPECPOWER )					// EFFECTSEMANTICID_MATERIALSPECPOWER,
		DEFINE_SEMANTIC( FOGSTART )								// EFFECTSEMANTICID_FOGSTART,
		DEFINE_SEMANTIC( FOGRANGE )								// EFFECTSEMANTICID_FOGRANGE,
		DEFINE_SEMANTIC( FOGCOLOUR )							// EFFECTSEMANTICID_FOGCOLOUR,
		DEFINE_SEMANTIC( LIGHTBRIGHTNESS )						// EFFECTSEMANTICID_CAMERAPOSITION,
		DEFINE_SEMANTIC( LIGHTPOSITION )						// EFFECTSEMANTICID_LIGHTPOSITION,
		DEFINE_SEMANTIC( LIGHTDIRECTION )						// EFFECTSEMANTICID_LIGHTDIRECTION,
		DEFINE_SEMANTIC( LIGHTDIFFUSE )							// EFFECTSEMANTICID_LIGHTDIFFUSE,
		DEFINE_SEMANTIC( LIGHTSPECULAR )						// EFFECTSEMANTICID_LIGHTSPECULAR,
		DEFINE_SEMANTIC( LIGHTMINRADIUS )						// EFFECTSEMANTICID_LIGHTMINRADIUS,
		DEFINE_SEMANTIC( LIGHTMAXRADIUS )						// EFFECTSEMANTICID_LIGHTMAXRADIUS,
		DEFINE_SEMANTIC( LIGHTEXPONENT )						// EFFECTSEMANTICID_LIGHTEXPONENT,
		DEFINE_SEMANTIC( LIGHTFALLOFF )							// EFFECTSEMANTICID_LIGHTFALLOFF,
		DEFINE_SEMANTIC( DIFFUSETEXTURE0 )						// EFFECTSEMANTICID_DIFFUSETEXTURE0,
		DEFINE_SEMANTIC( DIFFUSETEXTURE1 )						// EFFECTSEMANTICID_DIFFUSETEXTURE1,
		DEFINE_SEMANTIC( DIFFUSETEXTURE2 )						// EFFECTSEMANTICID_DIFFUSETEXTURE2,
		DEFINE_SEMANTIC( DIFFUSETEXTURE3 )						// EFFECTSEMANTICID_DIFFUSETEXTURE3,
		DEFINE_SEMANTIC( NORMALTEXTURE )						// EFFECTSEMANTICID_NORMALTEXTURE,
		DEFINE_SEMANTIC( SPECULARTEXTURE )						// EFFECTSEMANTICID_SPECULARTEXTURE,
		DEFINE_SEMANTIC( LIGHTMAPTEXTURE )						// EFFECTSEMANTICID_LIGHTMAPTEXTURE,
		DEFINE_SEMANTIC( SHADOWMAPTEXTURE )						// EFFECTSEMANTICID_SHADOWMAPTEXTURE,

		NULL,
	};

}
}