/********************************************************************
    Written by James Moran
    Please see the file HEART_LICENSE.txt in the source's root directory.
*********************************************************************/
#pragma once

#ifndef luaFILESYSTEM_H__
#define luaFILESYSTEM_H__

#ifdef __cplusplus
extern "C" {
#endif
#   include "lua.h"
#   include "lauxlib.h"
#   include "lualib.h"
#ifdef __cplusplus
}//extern "C" {
#endif

#ifdef _WINDLL
#   define luaFILESYSTEM_SHARED_LIB
#endif

#ifdef luaFILESYSTEM_SHARED_LIB
#   ifdef lua_filesystem_EXPORTS //generated by cmake
#       define luaFILESYSTEM_EXPORT __declspec(dllexport)
#   else
#       define luaFILESYSTEM_EXPORT __declspec(dllimport)
#   endif
#   define luaFILESYSTEM_API          __cdecl
#else
#   define luaFILESYSTEM_EXPORT extern
#   define luaFILESYSTEM_API 
#endif

#ifdef __cplusplus
extern "C" {
#endif
luaFILESYSTEM_EXPORT int luaFILESYSTEM_API luaopen_filesystem(lua_State *L);
#ifdef __cplusplus
}//extern "C" {
#endif

#endif // luaFILESYSTEM_H__
