/********************************************************************

    filename:   lua_filesystem.h  
    
    Copyright (c) 1:4:2013 James Moran
    
    This software is provided 'as-is', without any express or implied
    warranty. In no event will the authors be held liable for any damages
    arising from the use of this software.
    
    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:
    
    1. The origin of this software must not be misrepresented; you must not
    claim that you wrote the original software. If you use this software
    in a product, an acknowledgment in the product documentation would be
    appreciated but is not required.
    
    2. Altered source versions must be plainly marked as such, and must not be
    misrepresented as being the original software.
    
    3. This notice may not be removed or altered from any source
    distribution.

*********************************************************************/

#pragma once

#ifndef luaFILESYSTEM_H__
#define luaFILESYSTEM_H__

#include <boost/smart_ptr.hpp>

#ifdef _WINDLL
#   define luaFILESYSTEM_SHARED_LIB
#endif

#ifdef luaFILESYSTEM_SHARED_LIB
#   ifdef lua_filesystem_EXPORTS //generated by cmake
#       define luaFILESYSTEM_EXPORT __declspec(dllexport)
#   else
#       define luaFILESYSTEM_EXPORT __declspec(dllimport)
#   endif
#else
#   define luaFILESYSTEM_EXPORT extern
#endif

#define luaFILESYSTEM_API          __cdecl

#ifdef __cplusplus
extern "C" {
#endif
luaFILESYSTEM_EXPORT int luaFILESYSTEM_API luaopen_filesystem(lua_State *L);
#ifdef __cplusplus
}//extern "C" {
#endif

#endif // luaFILESYSTEM_H__